In [3]:
import pandas as pd
import torch
from transformers import BertTokenizer, BertForSequenceClassification
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split

In [5]:
df = pd.read_csv('sentiment_results.csv')
df.head()

,tweets,lemmatized_tweets,vader_sentiment,textblob_sentiment,vader_compound,textblob_polarity,textblob_subjectivity,sentiment
0,Monkey pox,Monkey pox,0,-1,0.0000,-0.050000,0.000000,Neutral
1,course new scam monkey pox,course new scam monkey pox,-1,1,-0.5719,0.043182,0.227273,Negative
2,Monkeypox virtually avoided less random gay se...,Monkeypox virtually avoided less random gay se...,1,-1,0.1531,-0.083333,0.383333,Positive
3,event monkey pox spread dont sex man man,event monkey pox spread dont sex man man,0,-1,0.0000,-0.050000,0.000000,Neutral
4,dont ask source Ive got bad feeling trying get...,dont ask source Ive got bad feeling trying get...,-1,-1,-0.4588,-0.700000,0.666667,Negative

In [6]:
df['sentiment'] = df['vader_compound'].apply(lambda x: 1 if x > 0 else (0 if x < 0 else 2))
df.head()

,tweets,lemmatized_tweets,vader_sentiment,textblob_sentiment,vader_compound,textblob_polarity,textblob_subjectivity,sentiment
0,Monkey pox,Monkey pox,0,-1,0.0000,-0.050000,0.000000,2
1,course new scam monkey pox,course new scam monkey pox,-1,1,-0.5719,0.043182,0.227273,0
2,Monkeypox virtually avoided less random gay se...,Monkeypox virtually avoided less random gay se...,1,-1,0.1531,-0.083333,0.383333,1
3,event monkey pox spread dont sex man man,event monkey pox spread dont sex man man,0,-1,0.0000,-0.050000,0.000000,2
4,dont ask source Ive got bad feeling trying get...,dont ask source Ive got bad feeling trying get...,-1,-1,-0.4588,-0.700000,0.666667,0

In [9]:
train_texts, test_texts, train_labels, test_labels = train_test_split(df['tweets'], df['sentiment'], test_size=0.2, random_state=42)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [10]:
train_encodings = tokenizer(list(train_texts), truncation=True, padding=True, max_length=128)
test_encodings = tokenizer(list(test_texts), truncation=True, padding=True, max_length=128)

ValueError: Input is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers.