In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
clean_data = pd.read_csv('sentiment_results.csv')
clean_data.head()

,tweets,lemmatized_tweets,vader_sentiment,textblob_sentiment,vader_compound,textblob_polarity,textblob_subjectivity,sentiment
0,Monkey pox,Monkey pox,0,-1,0.0000,-0.050000,0.000000,Neutral
1,course new scam monkey pox,course new scam monkey pox,-1,1,-0.5719,0.043182,0.227273,Negative
2,Monkeypox virtually avoided less random gay se...,Monkeypox virtually avoided less random gay se...,1,-1,0.1531,-0.083333,0.383333,Positive
3,event monkey pox spread dont sex man man,event monkey pox spread dont sex man man,0,-1,0.0000,-0.050000,0.000000,Neutral
4,dont ask source Ive got bad feeling trying get...,dont ask source Ive got bad feeling trying get...,-1,-1,-0.4588,-0.700000,0.666667,Negative

In [3]:
tfidf_vectorizer = TfidfVectorizer(max_features=1000, ngram_range=(1,3))
X_tfid = tfidf_vectorizer.fit_transform(clean_data['lemmatized_tweets'].dropna())
tfidf_df = pd.DataFrame(X_tfid.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

In [5]:
new_df = pd.concat([clean_data.reset_index(drop=True), tfidf_df], axis=1)
new_df

,tweets,lemmatized_tweets,vader_sentiment,textblob_sentiment,vader_compound,textblob_polarity,textblob_subjectivity,sentiment,abc,able,...,yeah,year,yearold,yes,yesterday,yet,york,young,youre,zero
0,Monkey pox,Monkey pox,0,-1,0.0000,-0.050000,0.000000,Neutral,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,course new scam monkey pox,course new scam monkey pox,-1,1,-0.5719,0.043182,0.227273,Negative,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Monkeypox virtually avoided less random gay se...,Monkeypox virtually avoided less random gay se...,1,-1,0.1531,-0.083333,0.383333,Positive,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,event monkey pox spread dont sex man man,event monkey pox spread dont sex man man,0,-1,0.0000,-0.050000,0.000000,Neutral,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,dont ask source Ive got bad feeling trying get...,dont ask source Ive got bad feeling trying get...,-1,-1,-0.4588,-0.700000,0.666667,Negative,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82886,truly sexual transmission children Monkeypox C...,truly sexual transmission child Monkeypox Chec...,1,1,0.1027,0.500000,0.833333,Positive,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82887,vaccines finally available Recently BlaqOut CE...,vaccine finally available Recently BlaqOut CEO...,1,1,0.5994,0.192857,0.571429,Positive,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82888,Starting hour pm Sign join conversation hMPXV ...,Starting hour pm Sign join conversation hMPXV ...,1,1,0.6597,0.333333,0.366667,Positive,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82889,uptick monkeypox cases Dr Thomas Giordano prov...,uptick monkeypox case Dr Thomas Giordano provi...,1,1,0.6369,1.000000,0.300000,Positive,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82890,veterinarian strongly encourage anyone monkeyp...,veterinarian strongly encourage anyone monkeyp...,1,1,0.5859,0.311111,0.744444,Positive,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
new_df.fillna(0.0)

,tweets,lemmatized_tweets,vader_sentiment,textblob_sentiment,vader_compound,textblob_polarity,textblob_subjectivity,sentiment,abc,able,...,yeah,year,yearold,yes,yesterday,yet,york,young,youre,zero
0,Monkey pox,Monkey pox,0,-1,0.0000,-0.050000,0.000000,Neutral,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,course new scam monkey pox,course new scam monkey pox,-1,1,-0.5719,0.043182,0.227273,Negative,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Monkeypox virtually avoided less random gay se...,Monkeypox virtually avoided less random gay se...,1,-1,0.1531,-0.083333,0.383333,Positive,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,event monkey pox spread dont sex man man,event monkey pox spread dont sex man man,0,-1,0.0000,-0.050000,0.000000,Neutral,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,dont ask source Ive got bad feeling trying get...,dont ask source Ive got bad feeling trying get...,-1,-1,-0.4588,-0.700000,0.666667,Negative,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82886,truly sexual transmission children Monkeypox C...,truly sexual transmission child Monkeypox Chec...,1,1,0.1027,0.500000,0.833333,Positive,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
82887,vaccines finally available Recently BlaqOut CE...,vaccine finally available Recently BlaqOut CEO...,1,1,0.5994,0.192857,0.571429,Positive,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
82888,Starting hour pm Sign join conversation hMPXV ...,Starting hour pm Sign join conversation hMPXV ...,1,1,0.6597,0.333333,0.366667,Positive,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
82889,uptick monkeypox cases Dr Thomas Giordano prov...,uptick monkeypox case Dr Thomas Giordano provi...,1,1,0.6369,1.000000,0.300000,Positive,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
82890,veterinarian strongly encourage anyone monkeyp...,veterinarian strongly encourage anyone monkeyp...,1,1,0.5859,0.311111,0.744444,Positive,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
import gensim
from gensim.models import Word2Vec

tokenized_tweets = new_df['lemmatized_tweets'].dropna().apply(lambda x: x.split())

w2v_model = Word2Vec(sentences=tokenized_tweets, vector_size=100, window=5, min_count=2, workers=4)

def get_w2v_vector(tweet):
    words = tweet.split()
    word_vectors = [w2v_model.wv[word] for word in words if word in w2v_model.wv]
    return np.mean(word_vectors, axis=0) if word_vectors else np.zeros(100)

new_df['w2v_vector'] = new_df['lemmatized_tweets'].dropna().apply(lambda x: get_w2v_vector(x))

In [9]:
new_df.head(100)

,tweets,lemmatized_tweets,vader_sentiment,textblob_sentiment,vader_compound,textblob_polarity,textblob_subjectivity,sentiment,abc,able,...,year,yearold,yes,yesterday,yet,york,young,youre,zero,w2v_vector
0,Monkey pox,Monkey pox,0,-1,0.0000,-0.050000,0.000000,Neutral,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[-0.07337868, 1.4225389, 0.3576131, 1.5678174,..."
1,course new scam monkey pox,course new scam monkey pox,-1,1,-0.5719,0.043182,0.227273,Negative,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[-0.5935747, 0.9500704, -0.18600535, 0.4939604..."
2,Monkeypox virtually avoided less random gay se...,Monkeypox virtually avoided less random gay se...,1,-1,0.1531,-0.083333,0.383333,Positive,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[-0.7032314, -0.20700899, -0.0062593194, 0.351..."
3,event monkey pox spread dont sex man man,event monkey pox spread dont sex man man,0,-1,0.0000,-0.050000,0.000000,Neutral,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[-1.3697028, 0.3252402, -0.63424313, 0.3303261..."
4,dont ask source Ive got bad feeling trying get...,dont ask source Ive got bad feeling trying get...,-1,-1,-0.4588,-0.700000,0.666667,Negative,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[-0.5334356, 0.60460705, -0.19259208, 0.473174..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,’ getting nd monkey pox shot forcing us experi...,’ getting nd monkey pox shot forcing u experim...,0,-1,0.0000,-0.075000,0.125000,Neutral,0.0,0.0,...,0.236659,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[-0.5216228, 0.5748152, -0.24768157, 0.1255163..."
96,center LGBT LGBT much longer Monkeypox,center LGBT LGBT much longer Monkeypox,0,1,0.0000,0.050000,0.150000,Neutral,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[-0.46926966, 0.11864177, 0.051291496, 0.00872..."
97,Monkeypox outbreak Canada shows ‘ encouraging ...,Monkeypox outbreak Canada show ‘ encouraging ’...,1,0,0.5267,0.000000,0.000000,Positive,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[-0.30849028, -0.23039961, 0.03159067, -0.6422..."
98,LMAO still rampant COVID problem monkeypox ano...,LMAO still rampant COVID problem monkeypox ano...,1,1,0.7034,0.600000,1.000000,Positive,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[-0.47608548, 0.34958607, -0.12837335, 0.19526..."
99,’ really sorry ’ going sht Right ’ still onlin...,’ really sorry ’ going sht Right ’ still onlin...,1,1,0.8232,0.297143,0.627143,Positive,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[-0.6247362, 0.6393326, -0.53096336, 0.1832762..."

In [10]:
!pip install transformers datasets torch scikit-learn

Collecting transformers
  Downloading transformers-4.49.0-py3-none-any.whl.metadata (44 kB)
Collecting datasets
  Downloading datasets-3.4.1-py3-none-any.whl.metadata (19 kB)
Collecting torch
  Downloading torch-2.6.0-cp312-cp312-win_amd64.whl.metadata (28 kB)
Requirement already satisfied: scikit-learn in d:\anaconda\lib\site-packages (1.5.1)
Requirement already satisfied: filelock in d:\anaconda\lib\site-packages (from transformers) (3.13.1)
Collecting huggingface-hub<1.0,>=0.26.0 (from transformers)
  Downloading huggingface_hub-0.29.3-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in d:\anaconda\lib\site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in d:\anaconda\lib\site-packages (from transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in d:\anaconda\lib\site-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in d:\anaconda\lib\site-packages (from transformers) (2024.9.11)
Requirement already satisfied: requests in d:\anaconda\lib\site-packages (from transformers) (2.32.3)
Collecting tokenizers<0.22,>=0.21 (from transformers)
  Downloading tokenizers-0.21.1-cp39-abi3-win_amd64.whl.metadata (6.9 kB)
Collecting safetensors>=0.4.1 (from transformers)
  Downloading safetensors-0.5.3-cp38-abi3-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: tqdm>=4.27 in d:\anaconda\lib\site-packages (from transformers) (4.66.5)
Requirement already satisfied: pyarrow>=15.0.0 in d:\anaconda\lib\site-packages (from datasets) (16.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in d:\anaconda\lib\site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in d:\anaconda\lib\site-packages (from datasets) (2.2.2)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp312-cp312-win_amd64.whl.metadata (13 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py312-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in d:\anaconda\lib\site-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.6.1)
Requirement already satisfied: aiohttp in d:\anaconda\lib\site-packages (from datasets) (3.10.5)
Requirement already satisfied: typing-extensions>=4.10.0 in d:\anaconda\lib\site-packages (from torch) (4.11.0)
Requirement already satisfied: networkx in d:\anaconda\lib\site-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in d:\anaconda\lib\site-packages (from torch) (3.1.4)
Requirement already satisfied: setuptools in d:\anaconda\lib\site-packages (from torch) (75.1.0)
Collecting sympy==1.13.1 (from torch)
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\anaconda\lib\site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: scipy>=1.6.0 in d:\anaconda\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in d:\anaconda\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\anaconda\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in d:\anaconda\lib\site-packages (from aiohttp->datasets) (2.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in d:\anaconda\lib\site-packages (from aiohttp->datasets) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in d:\anaconda\lib\site-packages (from aiohttp->datasets) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in d:\anaconda\lib\site-packages (from aiohttp->datasets) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\anaconda\lib\site-packages (from aiohttp->datasets) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in d:\anaconda\lib\site-packages (from aiohttp->datasets) (1.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda\lib\site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\lib\site-packages (from requests->transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda\lib\site-packages (from requests->transformers) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\lib\site-packages (from requests->transformers) (2024.8.30)
Requirement already satisfied: colorama in d:\anaconda\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in d:\anaconda\lib\site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda\lib\site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda\lib\site-packages (from pandas->datasets) (2023.3)
Requirement already satisfied: six>=1.5 in d:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Downloading transformers-4.49.0-py3-none-any.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   --- ------------------------------------ 0.8/10.0 MB 6.7 MB/s eta 0:00:02
   --- ------------------------------------ 0.8/10.0 MB 6.7 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/10.0 MB 4.2 MB/s eta 0:00:02
   ----------- ---------------------------- 2.9/10.0 MB 3.7 MB/s eta 0:00:02
   ------------- -------------------------- 3.4/10.0 MB 3.6 MB/s eta 0:00:02
   ----------------- ---------------------- 4.5/10.0 MB 3.8 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/10.0 MB 3.8 MB/s eta 0:00:02
   ----------------------- ---------------- 5.8/10.0 MB 3.7 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/10.0 MB 3.5 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/10.0 MB 3.5 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/10.0 MB 3.4 MB/s eta 0:00:01
   ------------------------------- -------- 7.9/10.0 MB 3.4 MB/s eta 0:00:01
   --------------------------------- ------ 8.4/10.0 MB 3.2 MB/s eta 0:00:01
   ----------------------------------- ---- 8.9/10.0 MB 3.2 MB/s eta 0:00:01
   ------------------------------------ --- 9.2/10.0 MB 3.1 MB/s eta 0:00:01
   ------------------------------------- -- 9.4/10.0 MB 2.9 MB/s eta 0:00:01
   -------------------------------------- - 9.7/10.0 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 2.8 MB/s eta 0:00:00
Downloading datasets-3.4.1-py3-none-any.whl (487 kB)
Downloading torch-2.6.0-cp312-cp312-win_amd64.whl (204.1 MB)
   ---------------------------------------- 0.0/204.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/204.1 MB ? eta -:--:--
   ---------------------------------------- 0.5/204.1 MB 1.7 MB/s eta 0:02:02
   ---------------------------------------- 1.0/204.1 MB 1.8 MB/s eta 0:01:53
   ---------------------------------------- 1.3/204.1 MB 1.9 MB/s eta 0:01:49
   ---------------------------------------- 1.8/204.1 MB 1.8 MB/s eta 0:01:51
   ---------------------------------------- 1.8/204.1 MB 1.8 MB/s eta 0:01:51
   ---------------------------------------- 2.1/204.1 MB 1.6 MB/s eta 0:02:04
   ---------------------------------------- 2.4/204.1 MB 1.5 MB/s eta 0:02:11
    --------------------------------------- 2.6/204.1 MB 1.5 MB/s eta 0:02:11
    --------------------------------------- 2.9/204.1 MB 1.4 MB/s eta 0:02:20
    --------------------------------------- 3.1/204.1 MB 1.4 MB/s eta 0:02:27
    --------------------------------------- 3.1/204.1 MB 1.4 MB/s eta 0:02:27
    --------------------------------------- 3.4/204.1 MB 1.2 MB/s eta 0:02:44
    --------------------------------------- 3.4/204.1 MB 1.2 MB/s eta 0:02:44
    --------------------------------------- 3.4/204.1 MB 1.2 MB/s eta 0:02:44
    --------------------------------------- 3.4/204.1 MB 1.2 MB/s eta 0:02:44
    --------------------------------------- 3.4/204.1 MB 1.2 MB/s eta 0:02:44
    --------------------------------------- 3.4/204.1 MB 1.2 MB/s eta 0:02:44
    --------------------------------------- 3.7/204.1 MB 912.7 kB/s eta 0:03:40
    --------------------------------------- 3.7/204.1 MB 912.7 kB/s eta 0:03:40
    --------------------------------------- 3.7/204.1 MB 912.7 kB/s eta 0:03:40
    --------------------------------------- 3.7/204.1 MB 912.7 kB/s eta 0:03:40
    --------------------------------------- 3.7/204.1 MB 912.7 kB/s eta 0:03:40
    --------------------------------------- 3.7/204.1 MB 912.7 kB/s eta 0:03:40
    --------------------------------------- 3.9/204.1 MB 729.5 kB/s eta 0:04:35
    --------------------------------------- 3.9/204.1 MB 729.5 kB/s eta 0:04:35
    --------------------------------------- 3.9/204.1 MB 729.5 kB/s eta 0:04:35
    --------------------------------------- 3.9/204.1 MB 729.5 kB/s eta 0:04:35
    --------------------------------------- 4.2/204.1 MB 669.3 kB/s eta 0:04:59
    --------------------------------------- 4.2/204.1 MB 669.3 kB/s eta 0:04:59
    --------------------------------------- 4.2/204.1 MB 669.3 kB/s eta 0:04:59
    --------------------------------------- 4.2/204.1 MB 669.3 kB/s eta 0:04:59
    --------------------------------------- 4.2/204.1 MB 669.3 kB/s eta 0:04:59
    --------------------------------------- 4.5/204.1 MB 614.3 kB/s eta 0:05:26
    --------------------------------------- 4.5/204.1 MB 614.3 kB/s eta 0:05:26
    --------------------------------------- 4.5/204.1 MB 614.3 kB/s eta 0:05:26
    --------------------------------------- 4.5/204.1 MB 614.3 kB/s eta 0:05:26
    --------------------------------------- 4.7/204.1 MB 583.2 kB/s eta 0:05:42
    --------------------------------------- 4.7/204.1 MB 583.2 kB/s eta 0:05:42
    --------------------------------------- 4.7/204.1 MB 583.2 kB/s eta 0:05:42
    --------------------------------------- 4.7/204.1 MB 583.2 kB/s eta 0:05:42
    --------------------------------------- 5.0/204.1 MB 554.1 kB/s eta 0:06:00
    --------------------------------------- 5.0/204.1 MB 554.1 kB/s eta 0:06:00
    --------------------------------------- 5.0/204.1 MB 554.1 kB/s eta 0:06:00
   - -------------------------------------- 5.2/204.1 MB 539.4 kB/s eta 0:06:09
   - -------------------------------------- 5.2/204.1 MB 539.4 kB/s eta 0:06:09
   - -------------------------------------- 5.2/204.1 MB 539.4 kB/s eta 0:06:09
   - -------------------------------------- 5.2/204.1 MB 539.4 kB/s eta 0:06:09
   - -------------------------------------- 5.2/204.1 MB 539.4 kB/s eta 0:06:09
   - -------------------------------------- 5.5/204.1 MB 513.9 kB/s eta 0:06:27
   - -------------------------------------- 5.5/204.1 MB 513.9 kB/s eta 0:06:27
   - -------------------------------------- 5.5/204.1 MB 513.9 kB/s eta 0:06:27
   - -------------------------------------- 5.8/204.1 MB 506.2 kB/s eta 0:06:32
   - -------------------------------------- 5.8/204.1 MB 506.2 kB/s eta 0:06:32
   - -------------------------------------- 5.8/204.1 MB 506.2 kB/s eta 0:06:32
   - -------------------------------------- 5.8/204.1 MB 506.2 kB/s eta 0:06:32
   - -------------------------------------- 6.0/204.1 MB 492.8 kB/s eta 0:06:42
   - -------------------------------------- 6.0/204.1 MB 492.8 kB/s eta 0:06:42
   - -------------------------------------- 6.0/204.1 MB 492.8 kB/s eta 0:06:42
   - -------------------------------------- 6.0/204.1 MB 492.8 kB/s eta 0:06:42
   - -------------------------------------- 6.3/204.1 MB 483.0 kB/s eta 0:06:50
   - -------------------------------------- 6.3/204.1 MB 483.0 kB/s eta 0:06:50
   - -------------------------------------- 6.3/204.1 MB 483.0 kB/s eta 0:06:50
   - -------------------------------------- 6.3/204.1 MB 483.0 kB/s eta 0:06:50
   - -------------------------------------- 6.6/204.1 MB 473.7 kB/s eta 0:06:58
   - -------------------------------------- 6.6/204.1 MB 473.7 kB/s eta 0:06:58
   - -------------------------------------- 6.8/204.1 MB 476.6 kB/s eta 0:06:54
   - -------------------------------------- 6.8/204.1 MB 476.6 kB/s eta 0:06:54
   - -------------------------------------- 6.8/204.1 MB 476.6 kB/s eta 0:06:54
   - -------------------------------------- 7.1/204.1 MB 476.2 kB/s eta 0:06:54
   - -------------------------------------- 7.1/204.1 MB 476.2 kB/s eta 0:06:54
   - -------------------------------------- 7.1/204.1 MB 476.2 kB/s eta 0:06:54
   - -------------------------------------- 7.3/204.1 MB 473.3 kB/s eta 0:06:56
   - -------------------------------------- 7.3/204.1 MB 473.3 kB/s eta 0:06:56
   - -------------------------------------- 7.6/204.1 MB 475.0 kB/s eta 0:06:54
   - -------------------------------------- 7.6/204.1 MB 475.0 kB/s eta 0:06:54
   - -------------------------------------- 7.6/204.1 MB 475.0 kB/s eta 0:06:54
   - -------------------------------------- 7.6/204.1 MB 475.0 kB/s eta 0:06:54
   - -------------------------------------- 7.9/204.1 MB 467.4 kB/s eta 0:07:00
   - -------------------------------------- 7.9/204.1 MB 467.4 kB/s eta 0:07:00
   - -------------------------------------- 7.9/204.1 MB 467.4 kB/s eta 0:07:00
   - -------------------------------------- 7.9/204.1 MB 467.4 kB/s eta 0:07:00
   - -------------------------------------- 7.9/204.1 MB 467.4 kB/s eta 0:07:00
   - -------------------------------------- 8.1/204.1 MB 452.6 kB/s eta 0:07:14
   - -------------------------------------- 8.1/204.1 MB 452.6 kB/s eta 0:07:14
   - -------------------------------------- 8.1/204.1 MB 452.6 kB/s eta 0:07:14
   - -------------------------------------- 8.1/204.1 MB 452.6 kB/s eta 0:07:14
   - -------------------------------------- 8.1/204.1 MB 452.6 kB/s eta 0:07:14
   - -------------------------------------- 8.4/204.1 MB 444.5 kB/s eta 0:07:21
   - -------------------------------------- 8.4/204.1 MB 444.5 kB/s eta 0:07:21
   - -------------------------------------- 8.4/204.1 MB 444.5 kB/s eta 0:07:21
   - -------------------------------------- 8.4/204.1 MB 444.5 kB/s eta 0:07:21
   - -------------------------------------- 8.4/204.1 MB 444.5 kB/s eta 0:07:21
   - -------------------------------------- 8.4/204.1 MB 444.5 kB/s eta 0:07:21
   - -------------------------------------- 8.7/204.1 MB 426.4 kB/s eta 0:07:39
   - -------------------------------------- 8.7/204.1 MB 426.4 kB/s eta 0:07:39
   - -------------------------------------- 8.7/204.1 MB 426.4 kB/s eta 0:07:39
   - -------------------------------------- 8.7/204.1 MB 426.4 kB/s eta 0:07:39
   - -------------------------------------- 8.9/204.1 MB 421.7 kB/s eta 0:07:43
   - -------------------------------------- 8.9/204.1 MB 421.7 kB/s eta 0:07:43
   - -------------------------------------- 8.9/204.1 MB 421.7 kB/s eta 0:07:43
   - -------------------------------------- 9.2/204.1 MB 420.7 kB/s eta 0:07:44
   - -------------------------------------- 9.2/204.1 MB 420.7 kB/s eta 0:07:44
   - -------------------------------------- 9.2/204.1 MB 420.7 kB/s eta 0:07:44
   - -------------------------------------- 9.4/204.1 MB 420.3 kB/s eta 0:07:44
   - -------------------------------------- 9.4/204.1 MB 420.3 kB/s eta 0:07:44
   - -------------------------------------- 9.4/204.1 MB 420.3 kB/s eta 0:07:44
   - -------------------------------------- 9.4/204.1 MB 420.3 kB/s eta 0:07:44
   - -------------------------------------- 9.7/204.1 MB 415.7 kB/s eta 0:07:48
   - -------------------------------------- 9.7/204.1 MB 415.7 kB/s eta 0:07:48
   - -------------------------------------- 9.7/204.1 MB 415.7 kB/s eta 0:07:48
   - -------------------------------------- 9.7/204.1 MB 415.7 kB/s eta 0:07:48
   - ------------------------------------- 10.0/204.1 MB 414.1 kB/s eta 0:07:49
   - ------------------------------------- 10.0/204.1 MB 414.1 kB/s eta 0:07:49
   - ------------------------------------- 10.0/204.1 MB 414.1 kB/s eta 0:07:49
   - ------------------------------------- 10.0/204.1 MB 414.1 kB/s eta 0:07:49
   - ------------------------------------- 10.0/204.1 MB 414.1 kB/s eta 0:07:49
   - ------------------------------------- 10.2/204.1 MB 407.6 kB/s eta 0:07:56
   - ------------------------------------- 10.2/204.1 MB 407.6 kB/s eta 0:07:56
   - ------------------------------------- 10.2/204.1 MB 407.6 kB/s eta 0:07:56
   - ------------------------------------- 10.2/204.1 MB 407.6 kB/s eta 0:07:56
   - ------------------------------------- 10.2/204.1 MB 407.6 kB/s eta 0:07:56
   - ------------------------------------- 10.2/204.1 MB 407.6 kB/s eta 0:07:56
   -- ------------------------------------ 10.5/204.1 MB 396.1 kB/s eta 0:08:09
   -- ------------------------------------ 10.5/204.1 MB 396.1 kB/s eta 0:08:09
   -- ------------------------------------ 10.5/204.1 MB 396.1 kB/s eta 0:08:09
   -- ------------------------------------ 10.5/204.1 MB 396.1 kB/s eta 0:08:09
   -- ------------------------------------ 10.7/204.1 MB 394.8 kB/s eta 0:08:10
   -- ------------------------------------ 10.7/204.1 MB 394.8 kB/s eta 0:08:10
   -- ------------------------------------ 10.7/204.1 MB 394.8 kB/s eta 0:08:10
   -- ------------------------------------ 11.0/204.1 MB 393.7 kB/s eta 0:08:11
   -- ------------------------------------ 11.0/204.1 MB 393.7 kB/s eta 0:08:11
   -- ------------------------------------ 11.0/204.1 MB 393.7 kB/s eta 0:08:11
   -- ------------------------------------ 11.0/204.1 MB 393.7 kB/s eta 0:08:11
   -- ------------------------------------ 11.3/204.1 MB 391.0 kB/s eta 0:08:14
   -- ------------------------------------ 11.3/204.1 MB 391.0 kB/s eta 0:08:14
   -- ------------------------------------ 11.3/204.1 MB 391.0 kB/s eta 0:08:14
   -- ------------------------------------ 11.3/204.1 MB 391.0 kB/s eta 0:08:14
   -- ------------------------------------ 11.3/204.1 MB 391.0 kB/s eta 0:08:14
   -- ------------------------------------ 11.3/204.1 MB 391.0 kB/s eta 0:08:14
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.5/204.1 MB 385.6 kB/s eta 0:08:20
   -- ------------------------------------ 11.8/204.1 MB 276.8 kB/s eta 0:11:35
   -- ------------------------------------ 11.8/204.1 MB 276.8 kB/s eta 0:11:35
   -- ------------------------------------ 11.8/204.1 MB 276.8 kB/s eta 0:11:35
   -- ------------------------------------ 11.8/204.1 MB 276.8 kB/s eta 0:11:35
   -- ------------------------------------ 11.8/204.1 MB 276.8 kB/s eta 0:11:35
   -- ------------------------------------ 11.8/204.1 MB 276.8 kB/s eta 0:11:35
   -- ------------------------------------ 11.8/204.1 MB 276.8 kB/s eta 0:11:35