In [15]:
import pandas as pd
import numpy as np
from datetime import datetime
import nltk

In [9]:
df=pd.read_csv('guardian_articles.csv')

In [11]:
df.head()

,article_id,sectionName,webTitle,webUrl,bodyContent,webPublicationDate,id
0,us-news/2016/jan/31/iowa-caucus-underdog-candi...,US news,Iowa underdogs put on brave faces despite all ...,https://www.theguardian.com/us-news/2016/jan/3...,As polling day looms and the cameras turn only...,2016-01-31T23:53:37Z,1
1,us-news/2016/jan/31/iowa-caucus-worlds-most-pa...,US news,Iowa caucus: hologram eagle and Jesus star on ...,https://www.theguardian.com/us-news/2016/jan/3...,"In Des Moines on Sunday, the Guardian was give...",2016-01-31T23:46:28Z,2
2,world/2016/jan/31/tanzania-britsh-helicopter-p...,World news,British pilot in Tanzania 'manoeuvred ​to save...,https://www.theguardian.com/world/2016/jan/31/...,A British pilot who was shot dead by an elepha...,2016-01-31T23:43:48Z,3
3,football/2016/jan/31/late-winner-gets-usa-off-...,Football,USA 3-2 Iceland | International friendly match...,https://www.theguardian.com/football/2016/jan/...,USA took a step toward shaking off the ghosts ...,2016-01-31T23:30:49Z,4
4,football/2016/jan/31/blackburn-paul-lambert-ox...,Football,Reinvigorated Paul Lambert reflects after impr...,https://www.theguardian.com/football/2016/jan/...,"The clean-shaven, spectacle free and suspiciou...",2016-01-31T22:30:10Z,5

In [13]:
df['sectionName'].unique()

array(['US news', 'World news', 'Football', 'Sport', 'Television & radio',
       'Guardian Small Business Network', 'News', 'Australia news',
       'Business', 'Opinion', 'Politics', 'Education', 'Money', 'UK news',
       'Books', 'Media', 'Life and style', 'Art and design', 'Film',
       'Stage', 'Music', 'Environment', "Children's books", 'Travel',
       'Science', 'Society', 'Technology', 'Guardian Careers', 'Fashion',
       'Guardian Sustainable Business', 'Culture', 'Food', 'Global',
       'Crosswords', 'Community', 'Law', 'Housing Network',
       'Working in development', 'Public Leaders Network',
       'Teacher Network', 'Cities', 'Guardian Masterclasses',
       'Global Development Professionals Network',
       'Healthcare Professionals Network', 'Women in Leadership',
       'Media Network', 'Global development',
       'Culture professionals network', 'Games',
       'Voluntary Sector Network', 'Social Care Network', 'Side Hustle',
       'GNM press office', 'Info', 'Membership', 'Guardian Foundation',
       'Weather', 'Help', 'From the Observer', 'Trade Boost',
       'From the Guardian', 'Inequality', 'Sustainability',
       'Salesforce: The Unfair Advantage', 'Guardian US press office',
       'Society Professionals', 'Personal Investments',
       'Guardian Live Australia', 'wellbeing at work',
       'Observer Food Monthly awards', 'Cannes Lions',
       'Business to business', 'Animals farmed', 'New faces of tech',
       'Higher Education Network', 'Future-focused IT',
       'Destination NSW: Uncover the unspoilt South Coast',
       'Dairy Australia: Listen to your gut', 'Professional supplements',
       'Dairy Australia: Sustainable futures',
       'Cathay Pacific: Upgrade your experience', 'Focus',
       'The last taboo', 'SBS On Demand', 'OPSM: Life in focus',
       'Xero: Resilient business', 'Sonos: Hyper real',
       'Westpac Scholars: Rethink tomorrow',
       'Commonwealth Bank Australia: Next Chapter',
       'Dark Matter Distribution: The Leadership',
       'De Bortoli: Going green', 'Dairy Australia: The food matrix',
       'WEHI: Brighter together', 'Amazon Prime Video: Truth Seekers',
       'Australia Post: Creating connections',
       'Guardian Australia press office', 'Powershop: Power potential',
       'HBF: Healthy choices', 'Bank Australia: Collective good',
       'The University of Melbourne: Graduating Performances',
       'Destination NSW: Road Trips',
       'Bank Australia: People Australia Needs',
       'Felix Mobile: The only one', 'Brother: Doing business well',
       'About', 'SBS On Demand: Are You Addicted to Technology',
       'Tourism NT: Territory Art Trails',
       'Unicef Australia: World Immunisation Week 2021',
       'Dairy Australia: We need to talk', 'Square: Good business',
       "See if it's time to sell", 'Chromebook: Helping Chinatown',
       'Feasting with Ocado', 'WA Museum: Discovering Ancient Greece',
       'Mazda: Sustainable style',
       'Dairy Australia: Healthy sustainable diets', 'A time for Japan',
       'SBS On Demand: New Gold Mountain', 'HBF: Never Settle',
       "Helga's: Capturing kindness", 'GNM archive', 'Meta: Buy Blak',
       'Quest Apartment Hotels: As local as you like it',
       'SBS: A world of difference', 'The invested generation',
       'Curtin University: Why study law',
       'Michelin: Built to keep you moving', 'OPSM: Optimal health',
       'Plico: Renewable energy',
       'Westpac Foundation: Investing in social enterprise',
       'Sustainable home improvements', 'Specsavers: Liberty London',
       'Further education: share your skills', 'Kyco: Full transparency',
       'MG Motor: Switch to electric', 'BMW: Sustainable mobility',
       'Mirvac: Voyager',
       'Travel Associates: Get out there in the Red Centre',
       'Boutique Homes: My home my way',
       'Plan International Australia: Global Hunger Crisis Appeal',
       'Snooze: Investing In Sleep', 'Dairy Australia: fracture research',
       'The Fred Hollows Foundation: 30 years of restoring sight',
       'Marine Stewardship Council: Saltwater Schools',
       'You could be here', 'Connected thinking',
       'Seek: The new world of work',
       'Huelwear - clothes for the conscious', 'Rediscover tequila',
       'Macquarie: Home of electric vehicles', 'Dine: Hope Grows',
       'Leisure like a local', 'AMC+: Only the good stuff',
       'Cancer Council Victoria: Giving in Will',
       'The Life You Can Save: Effective giving',
       'A vision for better food',
       'Australian World Orchestra: Zubin Mehta',
       'OPSM: a vision for safer roads', 'Community of solvers',
       'When more of us play, all of us win',
       'The University of Notre Dame: Ethical education',
       'Celebrating women engineers 2022', 'IFAW: Help animals thrive',
       'Archie Rose: Tailored spirits'], dtype=object)

In [19]:
df['webPublicationDate'] = df['webPublicationDate'].apply(
    lambda x: datetime.strptime(x, "%Y-%m-%dT%H:%M:%SZ").strftime("%Y-%m-%d")
)

df.head()
columns_to_drop = ['article_id', 'webTitle', 'webUrl', 'id']
modified_df = df.drop(columns=columns_to_drop, axis=1)

In [21]:
modified_df.head()

,sectionName,bodyContent,webPublicationDate
0,US news,As polling day looms and the cameras turn only...,2016-01-31
1,US news,"In Des Moines on Sunday, the Guardian was give...",2016-01-31
2,World news,A British pilot who was shot dead by an elepha...,2016-01-31
3,Football,USA took a step toward shaking off the ghosts ...,2016-01-31
4,Football,"The clean-shaven, spectacle free and suspiciou...",2016-01-31

In [23]:
modified_df['sectionName'].value_counts().head(10)

sectionName
World news        15501
Opinion           12130
Football          10896
Sport             10376
Australia news     7844
US news            7480
Politics           7074
Business           6990
UK news            6481
Life and style     5773
Name: count, dtype: int64

In [25]:
modified_df['webPublicationDate'] = pd.to_datetime(modified_df['webPublicationDate']).dt.date

In [29]:
start_date = datetime.strptime('2018-01-01', '%Y-%m-%d').date()
end_date = datetime.strptime('2022-03-31', '%Y-%m-%d').date()
date_filtered_df = modified_df[(modified_df['webPublicationDate'] >= start_date) & (modified_df['webPublicationDate'] <= end_date)]

In [31]:
date_filtered_df['sectionName'].value_counts().head(10)

sectionName
World news        11269
Opinion            7912
Football           7135
Sport              6633
Australia news     5419
US news            5004
Business           4672
Politics           4606
UK news            4255
Life and style     3804
Name: count, dtype: int64

In [33]:
modified_df['webPublicationDate'] = pd.to_datetime(modified_df['webPublicationDate']).dt.date

In [35]:
start_date = datetime.strptime('2018-01-01', '%Y-%m-%d').date()
end_date = datetime.strptime('2022-03-31', '%Y-%m-%d').date()
date_filtered_df = modified_df[(modified_df['webPublicationDate'] >= start_date) & (modified_df['webPublicationDate'] <= end_date)]

In [39]:
section_names = ['World news','Opinion','Australia news','Politics','Business','UK news'
]
section_filtered_df = date_filtered_df[date_filtered_df['sectionName'].isin(section_names)]

new_file_path = '/Users/Nikita/NLP/filtered_guardian_articles.csv'
section_filtered_df.to_csv(new_file_path, index=False)

In [37]:
pwd

'C:\\Users\\Nikita\\NLP'

In [41]:
filtered = pd.read_csv('filtered_guardian_articles.csv')
filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38133 entries, 0 to 38132
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sectionName         38133 non-null  object
 1   bodyContent         37938 non-null  object
 2   webPublicationDate  38133 non-null  object
dtypes: object(3)
memory usage: 893.9+ KB

In [43]:
filtered.head()

,sectionName,bodyContent,webPublicationDate
0,Politics,The government is to release a leaked Brexit a...,2018-01-31
1,World news,Twenty-two school children on their way to sta...,2018-01-31
2,Politics,Ireland’s deputy prime minister has warned it ...,2018-01-31
3,Australia news,The former prime minister Kevin Rudd is suing ...,2018-01-31
4,Business,"The Labor leader, Bill Shorten, on Tuesday sen...",2018-01-31

In [45]:
filtered['sectionName'].unique()

array(['Politics', 'World news', 'Australia news', 'Business', 'UK news',
       'Opinion'], dtype=object)

In [47]:
filtered['bodyContent'][0]

'The government is to release a leaked Brexit analysis that shows the UK economy would be significantly worse off in every modelled scenario after it decided not to oppose a Labour motion calling for the documents to be issued. The decision came as a second leak from the analysis emerged showing that tightening up Britain’s immigration system after Brexit would cause more economic damage than could be balanced out by any trade gains. The paper suggested the negative impact of a strict migration regime, in which free movement was replaced with a policy similar to that for non-EU migrants, would dwarf the 0.2% boost to economic growth from a US trade deal. And the study suggested such growth would even be cancelled out under a more relaxed immigration regime, according to the papers seen by BuzzFeed. The initial report on the leak revealed that it predicts the UK will end up economically worse off under three possible Brexit scenarios: a comprehensive free trade deal, single market access and no deal at all. Meanwhile a poll by the Best for Britain campaign group and YouGov showed shifting attitudes, with the public now expressing a preference for free trade with the EU over immigration controls. The shadow Brexit secretary, Keir Starmer, said the move to release the original analysis in full was “a victory for transparency and accountability” after the motion calling for the documents to be provided to MPs and the Brexit select committee was passed unanimously. Asked by Starmer about when the papers would be released, the Speaker, John Bercow, ruled it should happen “as a matter of urgency”, as decreed in the motion. After the debate, Starmer said Labour expected ministers to hand over the papers by the end of the week, though the exact timetable has yet to be determined. Speaking in the debate, the junior Brexit minister Robin Walker said some elements would be redacted if there was a possibility they could affect negotiations with the EU, and the studies would only be available to MPs in a confidential reading room. “A key part of this is for the government to be able to conduct internal thinking when it comes to preparing policy,” Walker said. The government has come under pressure to release the documents immediately and to the public, with the cross-party Treasury committee of MPs writing to David Davis, the Brexit secretary, asking for this to happen. “The document can hardly undermine the government’s negotiating position if it does not consider the government’s desired outcome,” the committee’s chair, Nicky Morgan, wrote. The climbdown came as Downing Street said Phillip Lee, a junior justice minister, had been reprimanded for tweeting that if such studies showed the economy would be harmed then a change in policy should follow. No such action has been taken against the Brexit minister Steve Baker, who said economic forecasts by government officials were “always wrong”. Ministers have dismissed the leaked analysis as interim and incomplete because it does not include the option of a bespoke deal with the EU, which is being sought by the government but about which details have yet to be explained. A Downing Street source said: “Phillip Lee will recognise that the analysis was initial and probably not worth commenting on. He has been spoken to by the chief whip and reminded that it is best to air his view in private.” Asked whether the lack of action against Baker meant the minister’s view was official government policy, the source said: “I will stick with what Steve Baker said.”'